from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Protocol

from qqbot.domain.models import (
    CancelledSlot,
    ExternalIdentity,
    Occupancy,
    RequestContext,
    Routine,
    TimeRange,
    User,
)


class BookingRepository(Protocol):
    site_id: str

    def initialize(self) -> None: ...
    def user_by_external(self, identity: ExternalIdentity) -> User | None: ...
    def bind_user(self, identity: ExternalIdentity, name: str, student_id: str) -> User: ...
    def user_by_name(self, name: str) -> User | None: ...
    def role_of(self, user_id: str) -> str: ...
    def set_role(self, user_id: str, role: str) -> None: ...
    def remove_role(self, user_id: str) -> None: ...
    def transfer_role(
        self, old_user_id: str, new_user_id: str, owner_role: str, fallback_role: str
    ) -> None: ...
    def book_available(
        self,
        context: RequestContext,
        room_id: str,
        target_date: date,
        requested: TimeRange,
        max_daily_minutes: int,
    ) -> list[TimeRange]: ...
    def cancel_user(
        self, user_id: str, target_date: date, room_id: str | None, requested: TimeRange | None
    ) -> list[CancelledSlot]: ...

    def cancel_all_user(self, user_id: str, from_date: date) -> list[CancelledSlot]:
        """软删本人从 from_date 起的全部未来预约（NLU「取消全部预约」）。"""

        ...

    def cancel_admin(self, target_date: date, room_id: str, requested: TimeRange) -> list[CancelledSlot]: ...
    def schedule(self, target_date: date, room_id: str | None = None) -> list[Occupancy]: ...
    def free_slots(
        self, target_date: date, room_ids: list[str], opening: TimeRange
    ) -> dict[str, list[TimeRange]]: ...
    def personal(self, user_id: str, from_date: date) -> list[tuple[date, str, TimeRange]]: ...
    def clear_date(self, target_date: date, actor_id: str) -> int: ...
    def undo_clear(self, target_date: date, actor_id: str) -> int: ...
    def add_routine(
        self, weekday: int, room_id: str, time_range: TimeRange, purpose: str, from_date: date
    ) -> Routine: ...
    def remove_routine(self, weekday: int, room_id: str, time_range: TimeRange) -> bool: ...
    def list_routines(self, weekday: int | None = None) -> list[Routine]: ...
    def backup_users(self) -> tuple[Path, int]: ...
    def restore_users(self) -> int: ...
    def cleanup_old(self, cutoff: date) -> int: ...
